<?php
namespace pantera\user\balance;

use yii\base\Module as BaseModule;

class Module extends BaseModule
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}