<?php

namespace pantera\user\balance\models;

use Yii;

/**
 * This is the model class for table "users_balance_history".
 *
 * @property int $id
 * @property int $user_id
 * @property string $sum
 * @property string $method
 * @property string $comment
 * @property string $created_at
 */
class UsersBalanceHistory extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%users_balance_history}}';
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord && empty($this->comment)){
            $this->comment = 'Баланс изменен администратором';
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id'], 'integer'],
            [['sum'], 'number'],
            [['comment'], 'string'],
            [['created_at'], 'safe'],
            [['method'], 'string', 'max' => 31],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'Пользователь',
            'sum' => 'Сумма',
            'method' => 'Способ',
            'comment' => 'Комментарий',
            'created_at' => 'Дата транзакции',
        ];
    }
}
